spring:  
  application:
    name: product-service
  rabbitmq:
    host: localhost
    port: 5672
  cloud:  
    stream:
      bindings:
        output:
          destination: orders-in
        input:
          destination: orders-out
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: direct
              routingKeyExpression: '"#"'
                     
server:  
  port: ${PORT:8093}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
